-- Create the merged beneficiary+claims table (LEFT JOIN from BIS).
-- Run this in the BigQuery Console query editor (your login has write access;
-- the app service account is read-only by design and cannot create tables).
--
-- Semantics: one row per beneficiary-claim. Every registered beneficiary appears;
-- beneficiaries with no claim (household members + all 7 brownfield states) have
-- NULL in every tms_* column. A beneficiary with N claims produces N rows.

CREATE OR REPLACE TABLE `nha-conversational-analytics.nha_conversational_analytics.BIS_TMS_Sample_Merged` AS
SELECT
  b.id_pk,
  b.ben_id,
  b.family_id,
  b.member_id,
  b.bis_family_id,
  b.bis_member_id,
  b.ben_ref_id,
  b.state_cd,
  b.dist_cd,
  b.block_id,
  b.village_id,
  b.rural_urban_flag,
  b.house_no,
  b.pincode,
  b.address,
  b.dist_name,
  b.state_name,
  b.ben_mobile_no,
  b.ben_email_id,
  b.json_obj_ben_source_dtl,
  b.json_obj_ben_ekyc_dtl,
  b.obj_aadhar_vault,
  b.active_status,
  b.enrl_status,
  b.created_by,
  b.created_dt,
  b.updated_by,
  b.updated_dt,
  b.abha_id,
  b.payer_id,
  b.tpa_isa_id,
  b.json_obj_ben_othr_dtl,
  b.src_flag,
  b.aadhaar_no,
  b.enrol_status,
  b.entity_id,
  b.card_no,
  b.photo,
  b.relation,
  b.auth_mode,
  b.primary_auth_mode,
  b.new_member_flag,
  b.gender,
  b.year_of_birth,
  b.name,
  b.father_name,
  b.age,
  b.primary_ben_id,
  b.approve_date,
  b.enrol_date,
  b.card_status,
  b.aadhar_status,
  b.reject_date,
  b.date_of_birth,
  b.scheme_code,
  b.request_type,
  b.auth_txn,
  b.primary_auth_txn,
  b.request_agent,
  b.match_score,
  b.source_type,
  b.aadhaar_disp_code,
  b.yob_secc,
  t.registration_id AS tms_registration_id,
  t.case_id AS tms_case_id,
  t.member_id AS tms_member_id,
  t.family_id AS tms_family_id,
  t.patient_name AS tms_patient_name,
  t.patient_dob AS tms_patient_dob,
  t.patient_state_code AS tms_patient_state_code,
  t.patient_district_code AS tms_patient_district_code,
  t.patient_district_name AS tms_patient_district_name,
  t.patient_state_name AS tms_patient_state_name,
  t.gender AS tms_gender,
  t.age AS tms_age,
  t.policy_code AS tms_policy_code,
  t.renewal_code AS tms_renewal_code,
  t.category_details AS tms_category_details,
  t.speciality_code AS tms_speciality_code,
  t.procedure_details AS tms_procedure_details,
  t.procedure_code AS tms_procedure_code,
  t.case_type AS tms_case_type,
  t.status_id_pk AS tms_status_id_pk,
  t.case_status AS tms_case_status,
  t.hospital_code AS tms_hospital_code,
  t.hospital_name AS tms_hospital_name,
  t.hosp_district_name AS tms_hosp_district_name,
  t.hosp_state_name AS tms_hosp_state_name,
  t.hospital_state_cd AS tms_hospital_state_cd,
  t.hospital_district_cd AS tms_hospital_district_cd,
  t.hosp_pan_number AS tms_hosp_pan_number,
  t.hospital_type AS tms_hospital_type,
  t.admission_dt AS tms_admission_dt,
  t.preauth_init_date AS tms_preauth_init_date,
  t.amount_preauth_initiated AS tms_amount_preauth_initiated,
  t.preauth_approved_date AS tms_preauth_approved_date,
  t.amount_preauth_approved AS tms_amount_preauth_approved,
  t.preauth_rejected_date AS tms_preauth_rejected_date,
  t.surgery_dt AS tms_surgery_dt,
  t.death_dt AS tms_death_dt,
  t.discharge_dt AS tms_discharge_dt,
  t.claim_init_date AS tms_claim_init_date,
  t.amount_claim_initiated AS tms_amount_claim_initiated,
  t.amount_claim_approved AS tms_amount_claim_approved,
  t.amount_claim_paid AS tms_amount_claim_paid,
  t.claim_rejected_date AS tms_claim_rejected_date,
  t.rf_amount AS tms_rf_amount,
  t.tds_amount AS tms_tds_amount,
  t.utr_no AS tms_utr_no,
  t.payment_paid_dt AS tms_payment_paid_dt,
  t.transaction_amount AS tms_transaction_amount,
  t.cpd_approved_date AS tms_cpd_approved_date,
  t.cpd_approved_amount AS tms_cpd_approved_amount,
  t.cpd_user AS tms_cpd_user,
  t.aco_approved_date AS tms_aco_approved_date,
  t.aco_approved_amount AS tms_aco_approved_amount,
  t.aco_user AS tms_aco_user,
  t.sha_approved_date AS tms_sha_approved_date,
  t.sha_approved_amount AS tms_sha_approved_amount,
  t.sha_user AS tms_sha_user,
  t.json_object_perauth AS tms_json_object_perauth,
  t.json_object_claim AS tms_json_object_claim,
  t.json_object_ben AS tms_json_object_ben,
  t.last_insert_dt AS tms_last_insert_dt,
  t.src_account_no AS tms_src_account_no,
  t.src_ifsc_code AS tms_src_ifsc_code,
  t.paid_flag AS tms_paid_flag,
  t.hosp_account_number AS tms_hosp_account_number,
  t.ben_ifsc_code AS tms_ben_ifsc_code,
  t.current_workflow_role AS tms_current_workflow_role,
  t.current_workflow_user AS tms_current_workflow_user,
  t.service_request_type AS tms_service_request_type,
  t.m_flag AS tms_m_flag,
  t.careplan_desc AS tms_careplan_desc,
  t.discharge_type AS tms_discharge_type,
  t.admission_type AS tms_admission_type,
  t.claim_approved_date AS tms_claim_approved_date,
  t.preauth_tat AS tms_preauth_tat,
  t.claim_tat AS tms_claim_tat,
  t.payment_tat AS tms_payment_tat,
  t.patient_mobile_number AS tms_patient_mobile_number
FROM `nha-conversational-analytics.nha_conversational_analytics.BIS_Sample` b
LEFT JOIN `nha-conversational-analytics.nha_conversational_analytics.TMS_Sample` t
  ON t.member_id = b.card_no;
